app:
  name: grader

log:
  level: debug
  encoding: json
  name: grader

web-server:
  host: localhost
  port: 8080
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  shutdown-timeout: 5s
  rate_limiter:
    type: fixed_window
    max_requests: 10
    interval: 1s

token:
  secret: 3z9KfP8vQwX2mLr7TnY5uB1sD4eH6jA0cVxRkUqWZpM=
  duration: 40m

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db-name: grader
  ssl-mode: disable
  time-zone: UTC
  pool:
    max-open-conns: 25
    max-idle-conns: 10
    conn-max-lifetime: 1h
    conn-max-idletime: 30m

s3-minio:
  endpoint: localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: grader
  use-ssl: false

grader:
  url: https://localhost:8022/api/v1/grader
  container: hw_checker
  workers: 3
  server:
    host: localhost
    port: 8022
    read-timeout: 10s
    write-timeout: 10s
    idle-timeout: 60s
    shutdown-timeout: 5s

message_queue:
  broker:
    active: rabbit
    rabbit:
      url: amqp://guest:guest@localhost:5672/
      exchange_type: direct
      durable: true
      prefetch: 20
      auto_declare: true
  messaging:
    channels:
      - name: grader
        target: https://localhost:8021
        api_path: /api/v1/grader
        rate_limiter:
          type: token_bucket
          max_requests: 100
          interval: 1s