app:
  name: grader

log:
  level: debug
  encoding: json
  name: grader

web-server:
  host: localhost
  port: 8080
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  shutdown-timeout: 5s

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db_name: queue
  ssl_mode: disable
  time_zone: UTC
  pool:
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: 1h
    conn_max_idle_time: 30m