app:
  name: grader

log:
  level: debug
  encoding: json
  name: grader

web-server:
  host: localhost
  port: 8080
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  shutdown-timeout: 5s