// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Login     string
	Name      string
	Password  string
	Admin     bool
	CreatedAt pgtype.Timestamptz
}
