// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatus string

const (
	OutboxStatusPending    OutboxStatus = "pending"
	OutboxStatusProcessing OutboxStatus = "processing"
	OutboxStatusFailed     OutboxStatus = "failed"
	OutboxStatusDone       OutboxStatus = "done"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusPending    ReviewStatus = "pending"
	ReviewStatusProcessing ReviewStatus = "processing"
	ReviewStatusFailed     ReviewStatus = "failed"
	ReviewStatusDone       ReviewStatus = "done"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus
	Valid        bool // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type OutboxReview struct {
	ID          int64
	EventID     pgtype.UUID
	Userid      pgtype.Int8
	Reviewid    pgtype.Int8
	Payload     []byte
	Status      OutboxStatus
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Attempts    pgtype.Int4
	MaxAttempts int32
	NextRetryAt pgtype.Timestamptz
	LastError   pgtype.Text
	ResultOut   pgtype.Text
}

type Review struct {
	ID        int64
	Userid    pgtype.Int8
	Task      int32
	Status    NullReviewStatus
	Attempts  pgtype.Int4
	CreatedAt pgtype.Timestamptz
	Fileid    pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type Task struct {
	ID                           int32
	Name                         pgtype.Text
	TargetFileName               pgtype.Text
	TargetFileValidation         pgtype.Bool
	TargetFileValidationLanguage pgtype.Text
}

type User struct {
	ID        int64
	Login     string
	Name      string
	Password  string
	Admin     bool
	CreatedAt pgtype.Timestamptz
}
