// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxReview = `-- name: CreateOutboxReview :exec
INSERT INTO outbox_reviews (event_id,
                            userid,
                            reviewid,
                            payload)
VALUES ($1, $2, $3, $4)
`

type CreateOutboxReviewParams struct {
	EventID  pgtype.UUID
	Userid   pgtype.Int8
	Reviewid pgtype.Int8
	Payload  []byte
}

func (q *Queries) CreateOutboxReview(ctx context.Context, arg CreateOutboxReviewParams) error {
	_, err := q.db.Exec(ctx, createOutboxReview,
		arg.EventID,
		arg.Userid,
		arg.Reviewid,
		arg.Payload,
	)
	return err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (userid, task, fileID)
VALUES ($1, $2, $3)
RETURNING id, userid, task, status, attempts, created_at, fileid, updated_at
`

type CreateReviewParams struct {
	Userid pgtype.Int8
	Task   int32
	Fileid pgtype.Text
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview, arg.Userid, arg.Task, arg.Fileid)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Task,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.Fileid,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, name, password)
VALUES ($1, $2, $3)
RETURNING id, login, name, password
`

type CreateUserParams struct {
	Login    string
	Name     string
	Password string
}

type CreateUserRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.Name, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOutboxReviewsBatch = `-- name: GetOutboxReviewsBatch :many
SELECT id, event_id, userid, reviewid, payload, status, created_at, processed_at, attempts, max_attempts, next_retry_at, last_error, result_out
FROM outbox_reviews
WHERE status = 'pending'
  AND attempts < max_attempts
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at
LIMIT 50 FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetOutboxReviewsBatch(ctx context.Context) ([]OutboxReview, error) {
	rows, err := q.db.Query(ctx, getOutboxReviewsBatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxReview
	for rows.Next() {
		var i OutboxReview
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Userid,
			&i.Reviewid,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.ResultOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxReviews = `-- name: GetPendingOutboxReviews :many
SELECT id, event_id, userid, reviewid, payload, status, created_at, processed_at, attempts, max_attempts, next_retry_at, last_error, result_out
FROM outbox_reviews
WHERE status = 'pending'
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at
LIMIT 50 FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxReviews(ctx context.Context) ([]OutboxReview, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxReview
	for rows.Next() {
		var i OutboxReview
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Userid,
			&i.Reviewid,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.ResultOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingReviews = `-- name: GetPendingReviews :many
SELECT id, userid, task, status, attempts, created_at, fileid, updated_at
FROM reviews
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.Query(ctx, getPendingReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Task,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.Fileid,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, userid, task, status, attempts, created_at, fileid, updated_at
FROM reviews
WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Task,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.Fileid,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewfileID = `-- name: GetReviewfileID :one
SELECT fileID
FROM reviews
WHERE id = $1
`

func (q *Queries) GetReviewfileID(ctx context.Context, id int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getReviewfileID, id)
	var fileid pgtype.Text
	err := row.Scan(&fileid)
	return fileid, err
}

const getReviewsAll = `-- name: GetReviewsAll :many
select users.id,
       users.login,
       users.name,
       tasks.id   as taskid,
       tasks.name as taskname,
       reviews.id as reviewid,
       reviews.status,
       reviews.created_at,
       reviews.updated_at
from users
         left join reviews on users.id = reviews.userid
         left join tasks on reviews.task = tasks.id
where users.admin = false
`

type GetReviewsAllRow struct {
	ID        int64
	Login     string
	Name      string
	Taskid    pgtype.Int4
	Taskname  pgtype.Text
	Reviewid  pgtype.Int8
	Status    NullReviewStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetReviewsAll(ctx context.Context) ([]GetReviewsAllRow, error) {
	rows, err := q.db.Query(ctx, getReviewsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsAllRow
	for rows.Next() {
		var i GetReviewsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Taskid,
			&i.Taskname,
			&i.Reviewid,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsByTask = `-- name: GetReviewsByTask :many
SELECT id, userid, task, status, attempts, created_at, fileid, updated_at
FROM reviews
WHERE task = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReviewsByTask(ctx context.Context, task int32) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByTask, task)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Task,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.Fileid,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsByUser = `-- name: GetReviewsByUser :many
SELECT id, userid, task, status, attempts, created_at, fileid, updated_at
FROM reviews
WHERE userid = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReviewsByUser(ctx context.Context, userid pgtype.Int8) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Task,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.Fileid,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsByUserID = `-- name: GetReviewsByUserID :many
select users.id,
       users.login,
       users.name,
       tasks.id   as taskid,
       tasks.name as taskname,
       reviews.id as reviewid,
       reviews.status,
       reviews.created_at,
       outbox_reviews.last_error,
       outbox_reviews.result_out
from users
         left join reviews on users.id = reviews.userid
         left join tasks on reviews.task = tasks.id
         left join outbox_reviews on reviews.id = outbox_reviews.reviewid
    and outbox_reviews.userid = users.id
where users.id = $1
`

type GetReviewsByUserIDRow struct {
	ID        int64
	Login     string
	Name      string
	Taskid    pgtype.Int4
	Taskname  pgtype.Text
	Reviewid  pgtype.Int8
	Status    NullReviewStatus
	CreatedAt pgtype.Timestamptz
	LastError pgtype.Text
	ResultOut pgtype.Text
}

func (q *Queries) GetReviewsByUserID(ctx context.Context, id int64) ([]GetReviewsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsByUserIDRow
	for rows.Next() {
		var i GetReviewsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Taskid,
			&i.Taskname,
			&i.Reviewid,
			&i.Status,
			&i.CreatedAt,
			&i.LastError,
			&i.ResultOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, name, password
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, name, password
FROM users
WHERE login = $1
`

type GetUserByLoginRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const isAdminByLogin = `-- name: IsAdminByLogin :one
SELECT admin
FROM users
WHERE login = $1
  AND admin = true
`

func (q *Queries) IsAdminByLogin(ctx context.Context, login string) (bool, error) {
	row := q.db.QueryRow(ctx, isAdminByLogin, login)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const isAdminByUseID = `-- name: IsAdminByUseID :one
SELECT admin
FROM users
WHERE ID = $1
  AND admin = true
`

func (q *Queries) IsAdminByUseID(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isAdminByUseID, id)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, name, password
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxReviewFailed = `-- name: MarkOutboxReviewFailed :exec
UPDATE outbox_reviews
SET attempts      = attempts + 1,
    next_retry_at = NOW() + ($2 * INTERVAL '1 second'),
    last_error    = $3
WHERE id = $1
`

type MarkOutboxReviewFailedParams struct {
	ID        int64
	Column2   interface{}
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxReviewFailed(ctx context.Context, arg MarkOutboxReviewFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxReviewFailed, arg.ID, arg.Column2, arg.LastError)
	return err
}

const markOutboxReviewFailedFinal = `-- name: MarkOutboxReviewFailedFinal :exec
UPDATE outbox_reviews
SET status     = 'failed',
    last_error = $2
WHERE id = $1
`

type MarkOutboxReviewFailedFinalParams struct {
	ID        int64
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxReviewFailedFinal(ctx context.Context, arg MarkOutboxReviewFailedFinalParams) error {
	_, err := q.db.Exec(ctx, markOutboxReviewFailedFinal, arg.ID, arg.LastError)
	return err
}

const markOutboxReviewProcessingOne = `-- name: MarkOutboxReviewProcessingOne :exec
UPDATE outbox_reviews
SET status       = 'processing',
    processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxReviewProcessingOne(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxReviewProcessingOne, id)
	return err
}

const markOutboxReviewRetry = `-- name: MarkOutboxReviewRetry :exec
UPDATE outbox_reviews
SET attempts      = attempts + 1,
    next_retry_at = NOW() + ($2 * INTERVAL '1 second'),
    last_error    = $3,
    status        = 'pending'
WHERE id = $1
`

type MarkOutboxReviewRetryParams struct {
	ID        int64
	Column2   interface{}
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxReviewRetry(ctx context.Context, arg MarkOutboxReviewRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxReviewRetry, arg.ID, arg.Column2, arg.LastError)
	return err
}

const markOutboxReviewStatus = `-- name: MarkOutboxReviewStatus :exec
UPDATE outbox_reviews
SET status     = $1,
    last_error = $2,
    result_out = $3
WHERE reviewid = $4
  AND userid = $5
`

type MarkOutboxReviewStatusParams struct {
	Status    OutboxStatus
	LastError pgtype.Text
	ResultOut pgtype.Text
	Reviewid  pgtype.Int8
	Userid    pgtype.Int8
}

func (q *Queries) MarkOutboxReviewStatus(ctx context.Context, arg MarkOutboxReviewStatusParams) error {
	_, err := q.db.Exec(ctx, markOutboxReviewStatus,
		arg.Status,
		arg.LastError,
		arg.ResultOut,
		arg.Reviewid,
		arg.Userid,
	)
	return err
}

const markOutboxReviewsProcessingMany = `-- name: MarkOutboxReviewsProcessingMany :exec
UPDATE outbox_reviews
SET status = 'processing'
WHERE id = ANY ($1::bigint[])
`

func (q *Queries) MarkOutboxReviewsProcessingMany(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markOutboxReviewsProcessingMany, dollar_1)
	return err
}

const markReviewStatus = `-- name: MarkReviewStatus :exec
UPDATE reviews
SET status = $1
WHERE id = $2
  AND userid = $3
  AND task = $4
`

type MarkReviewStatusParams struct {
	Status NullReviewStatus
	ID     int64
	Userid pgtype.Int8
	Task   int32
}

func (q *Queries) MarkReviewStatus(ctx context.Context, arg MarkReviewStatusParams) error {
	_, err := q.db.Exec(ctx, markReviewStatus,
		arg.Status,
		arg.ID,
		arg.Userid,
		arg.Task,
	)
	return err
}

const updateReviewStatus = `-- name: UpdateReviewStatus :exec
UPDATE reviews
SET status   = $2,
    attempts = attempts + 1
WHERE id = $1
`

type UpdateReviewStatusParams struct {
	ID     int64
	Status NullReviewStatus
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateReviewStatus, arg.ID, arg.Status)
	return err
}

const updateReviewStatusByID = `-- name: UpdateReviewStatusByID :exec
UPDATE reviews
SET status = $1
WHERE id = $2
`

type UpdateReviewStatusByIDParams struct {
	Status NullReviewStatus
	ID     int64
}

func (q *Queries) UpdateReviewStatusByID(ctx context.Context, arg UpdateReviewStatusByIDParams) error {
	_, err := q.db.Exec(ctx, updateReviewStatusByID, arg.Status, arg.ID)
	return err
}
