// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, name, password)
VALUES ($1, $2, $3) RETURNING id, login, name, password
`

type CreateUserParams struct {
	Login    string
	Name     string
	Password string
}

type CreateUserRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.Name, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, name, password
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, name, password
FROM users
WHERE login = $1
`

type GetUserByLoginRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT admin
FROM users
WHERE login = $1
  AND admin = true
`

func (q *Queries) IsAdmin(ctx context.Context, login string) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, login)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, name, password
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID       int64
	Login    string
	Name     string
	Password string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
